# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "office" do |ofc|
    ofc.vm.box = "windows/xp"
    ofc.vm.hostname = "office"
    ofc.vm.network "public_network", bridge: "enp2s0"
    ofc.vm.network "private_network", ip: "192.168.56.101"

    ofc.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
    end
  end
end
